import { mkdir } from 'fs/promises';
import path from 'path';
import { randomBytes } from 'crypto';

/**
 * Where uploaded files live, and how they are validated.
 *
 * Files used to be written into `public/uploads/`, which Next serves as static
 * assets. That had two consequences:
 *
 *  - Every uploaded photo was world-readable to anyone with the URL, with no
 *    session or story check. Once stories made content private between
 *    accounts, that was a cross-story leak by URL.
 *  - The stored extension came from the client's filename
 *    (`path.extname(file.name)`), so `evil.svg` or `evil.html` could be planted
 *    in a directory the web server happily serves - stored XSS on this origin.
 *    On a host that also runs PHP, a `.php` upload under a served root is worse
 *    than that.
 *
 * Files now live outside the web root and are streamed by
 * `app/api/media/[...path]/route.ts`, which authenticates first. Extensions are
 * chosen by this module from a sniffed content type, never from user input.
 */

/**
 * Default keeps everything inside the repo for local development, but outside
 * `public/` so nothing is statically served. Production should point this at a
 * directory that survives deploys - the app directory is replaced on each
 * release, so uploads must not live there.
 */
export const UPLOAD_ROOT =
  process.env.UPLOAD_DIR || path.join(process.cwd(), 'storage', 'uploads');

/** Buckets we accept writes into. Anything else is a programming error. */
export type UploadBucket = 'photos' | 'culinary';

export const MAX_UPLOAD_BYTES = 10 * 1024 * 1024; // 10MB

/**
 * Accepted image types, each mapped to the single extension we will write.
 * Deriving the extension here rather than from `file.name` is what stops a
 * crafted filename dictating what lands on disk.
 */
const ACCEPTED: Record<string, string> = {
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/gif': 'gif',
  'image/webp': 'webp',
};

/**
 * Magic-byte signatures. `file.type` is supplied by the client and trivially
 * spoofed, so the bytes are checked too and the two must agree.
 */
function sniffType(buffer: Buffer): string | null {
  if (buffer.length < 12) return null;

  // JPEG: FF D8 FF
  if (buffer[0] === 0xff && buffer[1] === 0xd8 && buffer[2] === 0xff) {
    return 'image/jpeg';
  }
  // PNG: 89 50 4E 47 0D 0A 1A 0A
  if (buffer.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) {
    return 'image/png';
  }
  // GIF: "GIF87a" / "GIF89a"
  if (buffer.subarray(0, 6).toString('latin1').match(/^GIF8[79]a$/)) {
    return 'image/gif';
  }
  // WebP: "RIFF" .... "WEBP"
  if (
    buffer.subarray(0, 4).toString('latin1') === 'RIFF' &&
    buffer.subarray(8, 12).toString('latin1') === 'WEBP'
  ) {
    return 'image/webp';
  }
  return null;
}

export interface ValidatedUpload {
  buffer: Buffer;
  mimeType: string;
  /** Server-generated, safe by construction. */
  fileName: string;
  size: number;
}

/**
 * Validate an uploaded file and decide the name it will be stored under.
 * Returns a plain error string rather than throwing, so routes can pass the
 * reason straight back to the user.
 */
export async function validateUpload(
  file: File,
  prefix = ''
): Promise<{ ok: true; value: ValidatedUpload } | { ok: false; error: string }> {
  if (file.size === 0) {
    return { ok: false, error: 'That file is empty.' };
  }
  if (file.size > MAX_UPLOAD_BYTES) {
    return { ok: false, error: 'Images must be 10MB or smaller.' };
  }

  const declared = (file.type || '').toLowerCase();
  if (!ACCEPTED[declared]) {
    return {
      ok: false,
      error: 'Only JPEG, PNG, GIF and WebP images are allowed.',
    };
  }

  const buffer = Buffer.from(await file.arrayBuffer());
  const sniffed = sniffType(buffer);

  if (!sniffed) {
    return { ok: false, error: 'That file does not look like an image.' };
  }
  // jpg/jpeg are the same bytes; otherwise the claim must match reality.
  if (sniffed !== declared) {
    return {
      ok: false,
      error: 'That file’s contents do not match its type.',
    };
  }

  const extension = ACCEPTED[sniffed];
  const unique = `${Date.now()}-${randomBytes(8).toString('hex')}`;

  return {
    ok: true,
    value: {
      buffer,
      mimeType: sniffed,
      fileName: `${prefix}${unique}.${extension}`,
      size: buffer.length,
    },
  };
}

/** Absolute directory for a bucket, created if absent. */
export async function bucketDir(bucket: UploadBucket): Promise<string> {
  const dir = path.join(UPLOAD_ROOT, bucket);
  await mkdir(dir, { recursive: true });
  return dir;
}

/**
 * Resolve a stored file name to an absolute path, refusing anything that
 * escapes its bucket. Names are generated by this module, but the media route
 * resolves values coming off the URL, so it is checked there too.
 */
export function resolveStoredFile(
  bucket: UploadBucket,
  fileName: string
): string | null {
  if (!fileName || fileName.includes('/') || fileName.includes('\\')) {
    return null;
  }
  if (fileName.includes('..') || path.basename(fileName) !== fileName) {
    return null;
  }

  const dir = path.join(UPLOAD_ROOT, bucket);
  const resolved = path.resolve(dir, fileName);
  if (!resolved.startsWith(path.resolve(dir) + path.sep)) return null;

  return resolved;
}

/** The URL the app stores and the client requests. */
export function mediaUrl(bucket: UploadBucket, fileName: string): string {
  return `/api/media/${bucket}/${fileName}`;
}

export function contentTypeFor(fileName: string): string {
  const ext = path.extname(fileName).slice(1).toLowerCase();
  const match = Object.entries(ACCEPTED).find(([, e]) => e === ext);
  return match ? match[0] : 'application/octet-stream';
}
